apiVersion: v1
kind: Service
metadata:
  name: service-backend-devops
  namespace: haproxy-controller-devops
spec:
  selector:
    app: ingress-default-backend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
